### ISSUE TITLE
Do you have any info on the API key in this project?

### ISSUE THREAD

**Issue by simon816** [Hakkin/scsearch#1]
This project has stopped working since the API security changes: https://developers.soundcloud.com/blog/security-updates-api

I'm wondering if you know anything about the API key in this project? I think a "client_secret" is now required.

Context is I'm trying to use the API to search SoundCloud but API keys are hard to come by as SC are not accepting new apps.

Thanks!

**Comment by Hakkin** [comment]
It seems it's no longer possible to have purely client-side applications that use the Soundcloud API since it requires fetching auth tokens using the client secret, which you can't share publicly. I'm not sure what Soundcloud's current policy is on giving out API keys, I got mine years ago and it seems it's still accessible in my account, but obviously only I can use it since you need the client secret now as well.

**Comment by simon816** [comment]
Thanks for the fast response! Yeah obviously a secret key is supposed to be kept secret. I was able to use their undocumented frontend API to do the searches I wanted to do (which is not as good as the official API).

You'd need to have a backend running to perform API calls without exposing the secret key. Best to do that if you intend on using it again.

FYI secret keys are quite valuable now there's a finite supply of them  :smile:  
https://old.reddit.com/r/soundcloud/comments/r95er7/looking_for_a_registered_soundcloud_app/
https://old.reddit.com/r/soundcloud/comments/7c3jbg/looking_for_an_already_existing_soundcloud/
